### PR TITLE
Improving the search experience

### PR DESCRIPTION
**Pull request by amrondonp**
When someone search, for example "FELIPE RESTREPO" it is not found because en database he is being persisted as "RESTREPO FELIPE", so this improvement, search for each keyword, separated by spaces. 

In the test can be seen which scenarios are considered and how the system is expected to behave.
'
Does it look good for you?

### CODE REVIEW

**Comment by amrondonp** [comment]
@Camiloasc1

**Comment by Camiloasc1** [comment]
There is a little problem with Heroku and Grails 2, but thanks!
[https://kb.heroku.com/grails-2-x-is-deprecated-with-support-ending-june-1-2017](https://kb.heroku.com/grails-2-x-is-deprecated-with-support-ending-june-1-2017)

**Comment by amrondonp** [comment]
Are we going to take down the page?

**Comment by amrondonp** [comment]
We should have used ruby :v

**Comment by Camiloasc1** [comment]
Or move to [openshift](https://www.openshift.com/) like @uncake

**Comment by amrondonp** [comment]
Yeah!, I think we made a good application, we need to do more marketing in the university

**Comment by Camiloasc1** [comment]
I'm also testing with [DeamHost](https://www.dreamhost.com/) by work reasons, looks pretty good and cheap.

**Comment by amrondonp** [comment]
What do you think about the change in the search?

**Comment by Camiloasc1** [comment]
Looks good to me
[Temporal deployment](https://un-app-pr-41.herokuapp.com/)

**Comment by amrondonp** [comment]
Cool heroku knows about lgtm's :D

**Pull request merged**
